### ISSUE TITLE
Process is killed

### ISSUE THREAD

**Issue by Silverster98** [Manishsinghrajput98/Deepfashion2_Training#1]
Your code is very helpful for me. Thank you for your work.
When I try to run your code, it prints `Epoch 1/30`, then the process was killed.

![image](https://user-images.githubusercontent.com/34436920/98531008-ac9a8000-22ba-11eb-9c35-9a7d7572e551.png)

Do you know the reason? Thanks for your reply.

My GPU is 1080ti with 8GB memory.

**Comment by Manishsinghrajput98** [comment]
Sir the issue is low memory
